### Base stage
FROM ubuntu:20.04 as base

RUN apt-get update
RUN apt-get install -y python3.8-dev python3-pip gcc 

CMD mkdir -p /app/src

WORKDIR /app
COPY ./requirements.txt .
RUN pip3 install -r ./requirements.txt

### Copy code stage
FROM base as code
WORKDIR /app
COPY . /app

### Debugging stage
WORKDIR /app/src
FROM code as debug
RUN pip3 install debugpy
ENTRYPOINT [ "python3", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "bot.py" ]